### ISSUE TITLE
Add fave.co to affiliate-tracking-domains

### ISSUE THREAD

**Issue by timkgh** [nextdns/click-tracking-domains#1]
It's a click-thru tracking domain used by deal sites, various legit shopping seems to break without it.

Note: it literally is `fave.co` it is not a .com typo.

**Comment by romaincointepas** [comment]
Fixed.

**Comment by timkgh** [comment]
Which list was it added to? I don't see it in https://raw.githubusercontent.com/nextdns/click-tracking-domains/main/domains

**Comment by romaincointepas** [comment]
The feature also includes the list from https://github.com/PeterDaveHello/url-shorteners/blob/master/list (`fave.co` is a url shortener domain).
